# Generated by Django 5.1.7 on 2025-04-02 09:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('itreporting', '0002_rename_date_subimtted_issue_date_subimitted'),
    ]

    operations = [
        migrations.RenameField(
            model_name='issue',
            old_name='date_subimitted',
            new_name='date_submitted',
        ),
    ]
