# Generated by Django 5.1.7 on 2025-04-28 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itreporting', '0003_rename_date_subimitted_issue_date_submitted'),
    ]

    operations = [
        migrations.CreateModel(
            name='Module',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('code', models.CharField(max_length=10, unique=True)),
                ('description', models.TextField()),
            ],
        ),
    ]
