# Generated by Django 5.1.7 on 2025-05-05 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('itreporting', '0004_module'),
    ]

    operations = [
        migrations.AddField(
            model_name='module',
            name='availability',
            field=models.CharField(choices=[('open', 'Open'), ('closed', 'Closed')], default='open', max_length=6),
        ),
        migrations.AddField(
            model_name='module',
            name='category',
            field=models.CharField(default='General', max_length=100),
        ),
        migrations.AddField(
            model_name='module',
            name='courses_allowed',
            field=models.ManyToManyField(related_name='modules', to='auth.group'),
        ),
        migrations.AddField(
            model_name='module',
            name='credit',
            field=models.PositiveIntegerField(default=3),
        ),
    ]
