# Generated by Django 5.1.7 on 2025-05-05 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itreporting', '0005_module_availability_module_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='module',
            name='category_type',
            field=models.CharField(choices=[('core', 'Core'), ('elective', 'Elective')], default='core', max_length=20),
        ),
    ]
