# Generated by Django 5.1.7 on 2025-05-05 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itreporting', '0007_enrollment_assessment_instructorprofile_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='module',
            name='category_type',
        ),
        migrations.AlterField(
            model_name='module',
            name='category',
            field=models.CharField(choices=[('core', 'Core'), ('elective', 'Elective'), ('general', 'General'), ('optional', 'Optional')], default='General', max_length=100),
        ),
    ]
